### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by kiroeko** [BlackWhitePandaBei/JavaLearen#1]
Does Porject means "project" in conin.java?

**Comment by BlackWhitePandaBei** [comment]
I have changed "Porject" to "Subject",it is means a course in college.

**Comment by BlackWhitePandaBei** [comment]
I have changed "Porject" to "Subject",it is means a course in college.

**Comment by BlackWhitePandaBei** [comment]
I have changed "Porject" to "Subject",it is means a course in college.
